name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Publish Typescript API
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: :simple-jdbc-api:publishTypescript
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish executable
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: :simple-jdbc-server:publish